# Generated by Django 5.0.14 on 2025-06-29 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='institution/')),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('heure_arrivee_attendue', models.TimeField(default='08:00')),
                ('heure_depart_attendue', models.TimeField(default='16:00')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presence.departement')),
            ],
            options={
                'ordering': ['nom', 'postnom'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('R', 'Retard'), ('F', 'Férié')], max_length=2)),
                ('type_travail', models.CharField(choices=[('P', 'Présentiel'), ('D', 'Demi-journée'), ('T', 'Télétravail')], default='P', max_length=1)),
                ('justification', models.FileField(blank=True, null=True, upload_to='justifications/')),
                ('remarques', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.agent')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='presence_pr_date_d6da48_idx'), models.Index(fields=['agent', 'date'], name='presence_pr_agent_i_27cd40_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
