# Generated by Django 5.0.14 on 2025-06-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='code',
        ),
    ]
