# Generated by Django 5.0.14 on 2025-06-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_remove_departement_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='fonction',
        ),
    ]
