# Generated by Django 5.0.14 on 2025-07-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_rename_departement_divisionetbureau_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='Division_Bureau',
        ),
        migrations.AddField(
            model_name='agent',
            name='prenom',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abrege', models.CharField(max_length=20)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureau_dirigee', to='presence.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='presence.bureau'),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abrege', models.CharField(max_length=20)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_dirigee', to='presence.agent')),
            ],
        ),
        migrations.AddField(
            model_name='bureau',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bureaux_directs', to='presence.direction'),
        ),
        migrations.AddField(
            model_name='agent',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents_sans_division', to='presence.direction'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abrege', models.CharField(max_length=20)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_dirigee', to='presence.agent')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='presence.direction')),
            ],
        ),
        migrations.AddField(
            model_name='bureau',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='presence.division'),
        ),
        migrations.AddField(
            model_name='agent',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents_sans_bureau', to='presence.division'),
        ),
        migrations.DeleteModel(
            name='DivisionEtBureau',
        ),
    ]
