# Generated by Django 5.0.14 on 2025-07-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_remove_agent_division_bureau_agent_prenom_bureau_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'AGENT', 'verbose_name_plural': 'AGENTS'},
        ),
        migrations.AlterModelOptions(
            name='bureau',
            options={'verbose_name': 'BUREAU', 'verbose_name_plural': 'BUREAUX'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'DIRECTION', 'verbose_name_plural': 'DIRECTIONS'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'DIVISION', 'verbose_name_plural': 'DIVISIONS'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'INSTITUTION', 'verbose_name_plural': 'INSTITUTIONS'},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'verbose_name': 'PRESENCE', 'verbose_name_plural': 'PRESENCES'},
        ),
        migrations.RemoveIndex(
            model_name='presence',
            name='presence_pr_date_d6da48_idx',
        ),
        migrations.RemoveIndex(
            model_name='presence',
            name='presence_pr_agent_i_27cd40_idx',
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='division',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la division"),
        ),
    ]
