# Generated by Django 5.0.14 on 2025-08-05 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_agent_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abrege', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage du grade")),
            ],
            options={
                'verbose_name': 'GRADE',
                'verbose_name_plural': 'GRADES',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='idgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='presence.grade'),
        ),
    ]
