# Generated by Django 5.0.14 on 2025-08-05 14:57

from django.db import migrations

def migrer_grades(apps, schema_editor):
    Agent = apps.get_model('presence', 'Agent')
    Grade = apps.get_model('presence', 'Grade')

    for agent in Agent.objects.all():
        nom_grade = agent.grade.strip() if agent.grade else None
        if nom_grade:
            grade_obj, _ = Grade.objects.get_or_create(nom=nom_grade)
            agent.idgrade = grade_obj
            agent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0009_grade_agent_idgrade'),
    ]

    operations = [
        migrations.RunPython(migrer_grades),
    ]
