# Generated by Django 5.0.14 on 2025-08-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0010_migrate_grade_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bureau',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage du bureau"),
        ),
    ]
