# Generated by Django 5.0.14 on 2025-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_bureau_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
